import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { SessionProviderAuth } from "@/components/providers/session-provider";
import { Navbar } from "@/components/Navbar";
import { QueryProvider } from "@/components/providers/query-provider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "QuizPro",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-background`}>
                <QueryProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <SessionProviderAuth>
                            <Navbar />
                            {children}
                        </SessionProviderAuth>
                    </ThemeProvider>
                </QueryProvider>
            </body>
        </html >
    );
}
